[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/registration"
  to = "/services/registration.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/pfesic"
  to = "/services/pfesic.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/labour"
  to = "/services/labour.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/payroll"
  to = "/services/payroll.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/shop"
  to = "/services/shop.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/contract"
  to = "/services/contract.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/epf"
  to = "/services/epf.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/posh"
  to = "/services/posh.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/factory"
  to = "/services/factory.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/bocw"
  to = "/services/bocw.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/fire"
  to = "/services/fire.html"
  status = 200
  force = false

[[redirects]]
  from = "/services/recruitment"
  to = "/services/recruitment.html"
  status = 200
  force = false

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
  force = false

[[redirects]]
  from = "/team"
  to = "/team.html"
  status = 200
  force = false

[[redirects]]
  from = "/careers"
  to = "/careers.html"
  status = 200
  force = false

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
  force = false

[[redirects]]
  from = "/insights"
  to = "/insights.html"
  status = 200
  force = false

[[redirects]]
  from = "/article-*"
  to = "/article-:splat"
  status = 200
  force = false
